from connectionSAP import connection
import time

# def selectall(session):
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("CHECK")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("STAT_IND")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("DOC_TYP_DESC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VBELN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("ITEM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("GSTIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("IRN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SERVER_DTL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BUKRS")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("TRAN_CATG")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("TRAN_TYP")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("DOC_TYP")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("DOC_NO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("DOC_DT")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_GSTIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_TRDNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_BNO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_BNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_LOC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_PIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_STCD")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_PH")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLFROM_EM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_GSTIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_TRDNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_BNO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_BNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_LOC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_PIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_STCD")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_PH")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("BILLTO_EM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_GSTIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_TRDNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_BNO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_BNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_LOC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_PIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_STCD")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_PH")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPFROM_EM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_GSTIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_TRDNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_BNO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_BNM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_LOC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_PIN")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_STCD")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_PH")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("SHIPTO_EM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_ASSVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_DISC")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_CGSTVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_SGSTVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_IGSTVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_OTHCHRG")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_CESVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_TOTINVVAL")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("VAL_DT_ROUNDOFF")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EXP_SHIPBNO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EXP_SHIPBDT")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EXP_PORT")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EXP_FORCUR")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EXP_CNTCODE")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("RFND_CLM")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EINV_ACK_NO")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectColumn("EINV_ACK_DATE")
#     session.findById("wnd[0]/usr/cntlSDCONT/shellcont/shell").selectedRows = "0"


def docnum(session,invoice_array):
    try:
        session.findById("wnd[0]/usr/ctxtSO_VBELN-LOW").text = invoice_array[0]
        session.findById("wnd[0]/usr/ctxtSO_VBELN-HIGH").text = invoice_array[-1]
        session.findById("wnd[0]/usr/radCREATE").select()
        print('Selecting Create E invoice')
        session.findById("wnd[0]").sendVKey(8)
    except Exception as e:
        
        print(e)
        return 'Error'

